name: news_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.16.6

dependencies:
  another_flushbar: ^1.12.29
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  faker: ^2.1.0
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.1
  get_it: ^7.2.0
  hydrated_bloc: ^9.1.0
  intl: ^0.18.1
  logger: ^2.0.2+1
  path_provider: ^2.0.12
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: null
  flutter_gen_runner: null
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/naviagtion/
    - assets/images/icons/

flutter_gen:
  output: lib/generated/
  assets:
    outputs:
      style: camel-case
  integrations:
    flutter_svg: true
