name: news_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.3

dependencies:
  bloc: ^8.1.1
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  intl: ^0.17.0
  logger: ^1.1.0
  path_provider: ^2.0.12
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: null
  flutter_gen_runner: null
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/naviagtion

flutter_gen:
  output: lib/generated/
  assets:
    outputs:
      style: camel-case
  integrations:
    flutter_svg: true
